/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesSitemapDotxmlRouteImport } from './routes/articles-sitemap[.]xml'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiArticleCoverUploadRouteImport } from './routes/api/article-cover-upload'
import { Route as ApiPublicArticleCoverSplatRouteImport } from './routes/api/public/article-cover/$'

const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSitemapDotxmlRoute = ArticlesSitemapDotxmlRouteImport.update({
  id: '/articles-sitemap.xml',
  path: '/articles-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticleCoverUploadRoute = ApiArticleCoverUploadRouteImport.update({
  id: '/api/article-cover-upload',
  path: '/api/article-cover-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticleCoverSplatRoute =
  ApiPublicArticleCoverSplatRouteImport.update({
    id: '/api/public/article-cover/$',
    path: '/api/public/article-cover/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/articles-sitemap.xml': typeof ArticlesSitemapDotxmlRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/api/article-cover-upload': typeof ApiArticleCoverUploadRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/public/article-cover/$': typeof ApiPublicArticleCoverSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/articles-sitemap.xml': typeof ArticlesSitemapDotxmlRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/api/article-cover-upload': typeof ApiArticleCoverUploadRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/public/article-cover/$': typeof ApiPublicArticleCoverSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/articles-sitemap.xml': typeof ArticlesSitemapDotxmlRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/api/article-cover-upload': typeof ApiArticleCoverUploadRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/public/article-cover/$': typeof ApiPublicArticleCoverSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/articles-sitemap.xml'
    | '/contact'
    | '/education'
    | '/api/article-cover-upload'
    | '/articles/$slug'
    | '/work/$slug'
    | '/articles/'
    | '/work/'
    | '/api/public/article-cover/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/articles-sitemap.xml'
    | '/contact'
    | '/education'
    | '/api/article-cover-upload'
    | '/articles/$slug'
    | '/work/$slug'
    | '/articles'
    | '/work'
    | '/api/public/article-cover/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/articles-sitemap.xml'
    | '/contact'
    | '/education'
    | '/api/article-cover-upload'
    | '/articles/$slug'
    | '/work/$slug'
    | '/articles/'
    | '/work/'
    | '/api/public/article-cover/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArticlesSitemapDotxmlRoute: typeof ArticlesSitemapDotxmlRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ApiArticleCoverUploadRoute: typeof ApiArticleCoverUploadRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  ApiPublicArticleCoverSplatRoute: typeof ApiPublicArticleCoverSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles-sitemap.xml': {
      id: '/articles-sitemap.xml'
      path: '/articles-sitemap.xml'
      fullPath: '/articles-sitemap.xml'
      preLoaderRoute: typeof ArticlesSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/article-cover-upload': {
      id: '/api/article-cover-upload'
      path: '/api/article-cover-upload'
      fullPath: '/api/article-cover-upload'
      preLoaderRoute: typeof ApiArticleCoverUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-cover/$': {
      id: '/api/public/article-cover/$'
      path: '/api/public/article-cover/$'
      fullPath: '/api/public/article-cover/$'
      preLoaderRoute: typeof ApiPublicArticleCoverSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArticlesSitemapDotxmlRoute: ArticlesSitemapDotxmlRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ApiArticleCoverUploadRoute: ApiArticleCoverUploadRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  ApiPublicArticleCoverSplatRoute: ApiPublicArticleCoverSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
